name: Build And Push Docker Image

on:
  push:
    branches:
      - develop # main으로 수정해야 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Gradle에 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3. Gradle Build
      - name: Build Project with Gradle
        run: |
          ./gradlew clean build
      # 4. 빌드 결과 확인 (선택적)
      - name: Verify build artifacts
        run: ls -al build/libs

  docker:
    runs-on: ubuntu-latest
    needs: build # build 작업이 완료된 후 실행
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Docker 설치 및 빌드 설정
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # 3. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker images
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t your-dockerhub-username/provocation-springboot-container:latest .
          docker images | grep provocation-springboot-container
          echo "Docker image build completed successfully."
          docker push your-dockerhub-username/provocation-springboot-container:latest
          echo "Docker image pushed successfully to Docker Hub."
